# This Dockerfile builds the API only

FROM python:3.7
WORKDIR /app

COPY api/requirements.txt api/.flaskenv api/api.py ./
RUN pip install -r ./requirements.txt

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
